### ISSUE TITLE
Tests are failing on Fedora 22

### ISSUE THREAD

**Issue by akurtakov** [rgrunber/fedoraproject-p2#9] opened 2015-06-25 08:48 UTC
Failed tests: 
  ArtifactRepositoryTest.existsFeatureInRepository:98 Artifact Repository must contain an IU referencing an artifact of type org.eclipse.update.feature.
  MetadataRepositoryTest.existsFeatureInRepository:107 Metadata Repository must contain an IU referencing an artifact of type org.eclipse.update.feature.
  InstallTest.bundleShapeDirUnitInstallTest:84->checkUnitInstallation:110 null

Tests run: 47, Failures: 3, Errors: 0, Skipped: 2

**Comment by akurtakov** [comment] 2015-06-25 08:49
org.eclipse.update.feature is long gone from platform so the test case needs adjusting.

**Comment by akurtakov** [comment] 2015-06-25 09:48
Found out #10 so this might not be an issue but can't verify until able to properly build.

**Comment by akurtakov** [comment] 2015-06-25 10:34
Verified that problem still exists with xmvn 2.4.0

**Comment by rgrunber** [comment] 2015-06-25 19:17
The solution would be to provide possible repos under a resources folder making the tests more reproducible. Basically the way the tests work now is they will use repos like /usr/share/java and /usr/lib*/eclipse/plugins, since that seemed easier than shipping repos in the tests.

'.. must contain an IU referencing an artifact of type org.eclipse.update.feature' refers to a unit whose type is 'org.eclipse.update.feature'. This is in fact looking for any feature, but it's looking in /usr/share/java which is a pretty bad place to find a feature (although emf/ecf should be under there).

**Comment by akurtakov** [comment] 2015-06-26 05:44
Since the introduction of eclipse-filesystem - emf/ecf install directly in _libdir/eclipse and are no longer symlinked from eclipes itself so no features in _javadir anymore.

**Comment by mbooth101** [comment] 2018-05-01 16:32
I just fixed all the test breakage on F28+ with Oxygen and Photon, so I'm closing this.

**Closed by mbooth101** 2018-05-01 16:32 UTC
